### ISSUE TITLE
connection broken: incompleteread

### ISSUE THREAD

**Issue by flok99** [careless25/lichess-bot#100]
--- Process Used. Total Queued: 0. Total Used: 1
+++ https://lichess.org/IXkbRUri/white UltraBullet vs BOT PepsiForAll(1500?)
ERROR:backoff:Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/IXkbRUri/move/0000)
Abandoning game due to connection error
Traceback (most recent call last):
  File "lichess-bot.py", line 135, in play_game
    li.make_move(game.id, best_move)
  File "/home/folkert/lichess-bot/lichess.py", line 72, in make_move
    return self.api_post(ENDPOINTS["move"].format(game_id, move))
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/home/folkert/lichess-bot/lichess.py", line 62, in api_post
    response.raise_for_status()
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/IXkbRUri/move/0000 
--- https://lichess.org/IXkbRUri/white Game over 
+++ Process Free. Total Queued: 0. Total Used: 0 
Process Process-2: 
Traceback (most recent call last): 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/urllib3/response.py", line 543, in _update_chunk_length 
    self.chunk_left = int(line, 16) 
ValueError: invalid literal for int() with base 16: b'' 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/urllib3/response.py", line 302, in _error_catcher 
    yield 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/urllib3/response.py", line 598, in read_chunked 
    self._update_chunk_length() 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/urllib3/response.py", line 547, in _update_chunk_length 
    raise httplib.IncompleteRead(line) 
http.client.IncompleteRead: IncompleteRead(0 bytes read) 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/requests/models.py", line 745, in generate 
    for chunk in self.raw.stream(chunk_size, decode_content=True): 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/urllib3/response.py", line 432, in stream 
    for line in self.read_chunked(amt, decode_content=decode_content): 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/urllib3/response.py", line 626, in read_chunked 
    self._original_response.close() 
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__ 
    self.gen.throw(type, value, traceback) 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/urllib3/response.py", line 320, in _error_catcher 
    raise ProtocolError('Connection broken: %r' % e, e) 
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)) 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap 
    self.run() 
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run 
    self._target(*self._args, **self._kwargs) 
  File "lichess-bot.py", line 35, in watch_control_stream 
    for evnt in li.get_event_stream().iter_lines(): 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/requests/models.py", line 789, in iter_lines 
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode): 
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/requests/models.py", line 748, in generate 
    raise ChunkedEncodingError(e) 
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by gbtami** [comment]
I think the fix of #82 solved this, so this can be closed also.
