### ISSUE TITLE
Error when trying to run "python lichess-bot.py -u"

### ISSUE THREAD

**Issue by BPTran91** [careless25/lichess-bot#117]
Hi,

I was trying to run Leela Engine on my computer; after the last step this error message appeared. Please help! Thank you very much in advance!

(abc) C:\Users\z3340\Desktop\abc>python lichess-bot.py -u
.   _/|
.  // o\
.  || ._)  lichess-bot 1.1.0
.  //__\
.  )___(   Play on Lichess with a bot

There appears to be a syntax problem with your config.yml
Traceback (most recent call last):
  File "lichess-bot.py", line 239, in <module>
    CONFIG = load_config(args.config or "./config.yml")
  File "C:\Users\z3340\Desktop\abc\config.py", line 11, in load_config
    raise e
  File "C:\Users\z3340\Desktop\abc\config.py", line 8, in load_config
    CONFIG = yaml.load(stream)
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\z3340\Desktop\abc\lib\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "./config.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "./config.yml", line 30, column 2

**Comment by krs013** [comment]
It looks like you made a typo when editing your `config.yml`, possibly on the first line. Make sure there aren’t any odd spaces or anything; the parser is really picky and brittle.

**Comment by krs013** [comment]
In particular you might be missing a quote mark in your api token but that is a guess.

**Comment by BPTran91** [comment]
Thank you for the reply.
Here is what my config.yml file look like on notepad++

![untitled](https://user-images.githubusercontent.com/39482147/40299628-e76d6644-5cb4-11e8-944a-0e8e7eb4722f.png)

**Comment by krs013** [comment]
Ok, I see it. There’s one space before the line starting with `lczero:` and there needs to be two. All of the lczero parameters after it (stopping before the line about silencing stderr) need to have four spaces, not three. Again, the format and the parser really are a pain, but that’s just it I guess. 

Also, since you’ve posted your api token online, you should get a new one. Log into the bot account on lichess, delete the old api token, and make a new one. Otherwise anyone who sees the screenshot could control your bot.

**Comment by BPTran91** [comment]
Thank you very much. Everything works now. I really appreciate your help :-)

**Comment by ddugovic** [comment]
You might want to regenerate your super-secret OAuth token.

**Comment by krs013** [comment]
Definitely do that. Also, if this is all wrapped up, please don’t forget to close the issue.
