### ISSUE TITLE
ERROR:backoff:Backing off api_get(...) for 0.6s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed c onnection without response',)))

### ISSUE THREAD

**Issue by drbeco** [careless25/lichess-bot#130]
Ok, went down to sleep and wake up with this log and Xadreco down.

Not even sure where to look, there is a bunch of cascade errors, exceptions appearing during exceptions handling.

The log starts at the very beginning of Xadreco being started. It plays a few moves, then something happens.

```
# [DEBUG file:xadreco.c line:596]: Starting optarg loop...
# DEBUG MACRO compiled value: 1
# Debug verbose level set at: 1
# play random: no. seed: -r 0
# connection: -c lichess
# wait: -x wait_xboard
# book: -b livro.txt
# Xadreco version 5.84 build 180626.010155 (C) 1994-2018, by Dr. Beco
# Xadreco comes with ABSOLUTELY NO WARRANTY;
# This is free software, and you are welcome to redistribute it
# under certain conditions; Please, visit http://www.fsf.org/licenses/gpl.html
# for details.

# scanf: xboard
# 
# feature done=0
# feature myname="Xadreco 5.84"
# feature ping=0 setboard=1 playother=1 san=0 usermove=0 time=1 draw=1 sigint=0 sigterm=1 reuse=0 analyze=1 variants="normal" colors=0 ics=0 name=0 p
ause=0 nps=0 debug=1 memory=0 smp=0 exclude=0 setscore=0
# feature done=1
# scanf: protover
# xboard: ignoring protover
# scanf: 2
# xboard: ignoring 2
# scanf: post
# xboard: post. Xadreco will show what its thinking. (1)
# scanf: easy
# xboard: easy. Xadreco stop thinking. (1)
# scanf: ping
# scanf: 123
# pong 123
# scanf: force
# xboard: setboard. Xadreco will set a board position.
# scanf: r7/pb1p4/3n4/1p3P1p/2pP1kB1/5prP/PP1N1R2/R6K
# xboard: r7/pb1p4/3n4/1p3P1p/2pP1kB1/5prP/PP1N1R2/R6K
# scanf: w
# xboard: w
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 0
# xboard: 0
# scanf: 29
# xboard: 29
# scanf: level
# scanf: 0
# scanf: 5:0
# scanf: 10
# xadreco level: 900.0s+10.0s por 60 lances: ajustado para st 15.000000 s por lance
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: r7/pb1p4/3n4/1p3P1p/2pP1k2/5BrP/PP1N1R2/R6K
# xboard: r7/pb1p4/3n4/1p3P1p/2pP1k2/5BrP/PP1N1R2/R6K
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 0
# xboard: 0
# scanf: 29
# xboard: 29
# scanf: time
# scanf: 31949.0
# scanf: otim
# scanf: 25716.0
# xadreco time: meu: 639.5s opo:577.2s, para 32 lances: ajustado para st 22.142228 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.57. Brancas. Tempo 1530073567.000000s. Acumulado: 1530073567.000000s. Hora: 2018-06-27 01:26:07
# move g3h3
# xadreco : N.58. Pretas. Tempo 23.000000s. Acumulado: 23.000000s. Hora: 2018-06-27 01:26:30
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: r7/pb1p4/3n4/1p3P1p/2pP1k2/5B1r/PP1N1R2/R5K1
# xboard: r7/pb1p4/3n4/1p3P1p/2pP1k2/5B1r/PP1N1R2/R5K1
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 1
# xboard: 1
# scanf: 30
# xboard: 30
# scanf: time
# scanf: 30661.0
# scanf: otim
# scanf: 26334.0
# xadreco time: meu: 306.6s opo:263.3s, para 31 lances: ajustado para st 11.515800 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.59. Brancas. Tempo 4.000000s. Acumulado: 4.000000s. Hora: 2018-06-27 01:26:34
# move h3g3
# xadreco : N.60. Pretas. Tempo 12.000000s. Acumulado: 12.000000s. Hora: 2018-06-27 01:26:46
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: r7/pb1p4/3n4/1p3P1p/2pP1k2/6r1/PP1N1RB1/R5K1
# xboard: r7/pb1p4/3n4/1p3P1p/2pP1k2/6r1/PP1N1RB1/R5K1
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 3
# xboard: 3
# scanf: 31
# xboard: 31
# scanf: time
# scanf: 30477.0
# scanf: otim
# scanf: 26318.0
# xadreco time: meu: 304.8s opo:263.2s, para 30 lances: ajustado para st 11.764414 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.61. Brancas. Tempo 11.000000s. Acumulado: 11.000000s. Hora: 2018-06-27 01:26:57
# move f4g5
# xadreco : N.62. Pretas. Tempo 12.000000s. Acumulado: 12.000000s. Hora: 2018-06-27 01:27:09
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: r7/pb1p4/3n4/1p3Pkp/2pP4/6r1/PP1N1RBK/R7
# xboard: r7/pb1p4/3n4/1p3Pkp/2pP4/6r1/PP1N1RBK/R7
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 5
# xboard: 5
# scanf: 32
# xboard: 32
# scanf: time
# scanf: 30229.0
# scanf: otim
# scanf: 21497.0
# xadreco time: meu: 302.3s opo:215.0s, para 29 lances: ajustado para st 14.657898 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.63. Brancas. Tempo 59.000000s. Acumulado: 59.000000s. Hora: 2018-06-27 01:28:08
# move g3g2
# xadreco : N.64. Pretas. Tempo 15.000000s. Acumulado: 15.000000s. Hora: 2018-06-27 01:28:23
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: r7/pb1p4/3n4/1p3Pkp/2pP4/8/PP1N2RK/R7
# xboard: r7/pb1p4/3n4/1p3Pkp/2pP4/8/PP1N2RK/R7
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 0
# xboard: 0
# scanf: 33
# xboard: 33
# scanf: time
# scanf: 29681.0
# scanf: otim
# scanf: 22157.0
# xadreco time: meu: 296.8s opo:221.6s, para 28 lances: ajustado para st 14.199991 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.65. Brancas. Tempo 4.000000s. Acumulado: 4.000000s. Hora: 2018-06-27 01:28:27
# move b7g2
# xadreco : N.66. Pretas. Tempo 15.000000s. Acumulado: 15.000000s. Hora: 2018-06-27 01:28:42
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: r7/p2p4/3n4/1p3Pkp/2pP4/8/PP1N2K1/R7
# xboard: r7/p2p4/3n4/1p3Pkp/2pP4/8/PP1N2K1/R7
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 0
# xboard: 0
# scanf: 34
# xboard: 34
# scanf: time
# scanf: 29147.0
# scanf: otim
# scanf: 20519.0
# xadreco time: meu: 291.5s opo:205.2s, para 27 lances: ajustado para st 15.334435 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.67. Brancas. Tempo 27.000000s. Acumulado: 27.000000s. Hora: 2018-06-27 01:29:09
# move a8e8
# xadreco : N.68. Pretas. Tempo 16.000000s. Acumulado: 16.000000s. Hora: 2018-06-27 01:29:25
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: 4r3/p2p4/3n4/1p3Pkp/2pP4/5N2/PP4K1/R7
# xboard: 4r3/p2p4/3n4/1p3Pkp/2pP4/5N2/PP4K1/R7
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 2
# xboard: 2
# scanf: 35
# xboard: 35
# scanf: time
# scanf: 28528.0
# scanf: otim
# scanf: 20394.0
# xadreco time: meu: 285.3s opo:203.9s, para 26 lances: ajustado para st 15.348534 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.69. Brancas. Tempo 12.000000s. Acumulado: 12.000000s. Hora: 2018-06-27 01:29:37
# move g5f5
# xadreco : N.70. Pretas. Tempo 16.000000s. Acumulado: 16.000000s. Hora: 2018-06-27 01:29:53
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: 4r3/p2p4/3n4/1p2Nk1p/2pP4/8/PP4K1/R7
# xboard: 4r3/p2p4/3n4/1p2Nk1p/2pP4/8/PP4K1/R7
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 1
# xboard: 1
# scanf: 36
# xboard: 36
# scanf: time
# scanf: 27886.0
# scanf: otim
# scanf: 21208.0
# xadreco time: meu: 278.9s opo:212.1s, para 25 lances: ajustado para st 14.666711 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.71. Brancas. Tempo 2.000000s. Acumulado: 2.000000s. Hora: 2018-06-27 01:29:55
# move e8e7
# xadreco : N.72. Pretas. Tempo 15.000000s. Acumulado: 15.000000s. Hora: 2018-06-27 01:30:10
# scanf: force
# xboard: force. Xadreco is in force mode.
# scanf: setboard
# xboard: setboard. Xadreco will set a board position.
# scanf: 8/p2pr3/3n4/1p2Nk1p/2pP4/8/PP4K1/5R2
# xboard: 8/p2pr3/3n4/1p2Nk1p/2pP4/8/PP4K1/5R2
# scanf: b
# xboard: b
# scanf: -
# xboard: -
# scanf: -
# xboard: -
# scanf: 3
# xboard: 3
# scanf: 37
# xboard: 37
# scanf: time
# scanf: 27404.0
# scanf: otim
# scanf: 21717.0
# xadreco time: meu: 274.0s opo:217.2s, para 24 lances: ajustado para st 14.408436 s por lance
# scanf: go
# xboard: go. Xadreco is now black.
# xadreco : N.73. Brancas. Tempo 6.000000s. Acumulado: 6.000000s. Hora: 2018-06-27 01:30:16
# move f5e4
# xadreco : N.74. Pretas. Tempo 15.000000s. Acumulado: 15.000000s. Hora: 2018-06-27 01:30:31
ERROR:backoff:Giving up watch_control_stream(...) after 2 tries (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
Process Process-2:
Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 543, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 547, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "lichess-bot.py", line 39, in watch_control_stream
    for evnt in li.get_event_stream().iter_lines():
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 789, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
# scanf: quit
# xadreco : # Thanks for playing Xadreco.
# xadreco : sai ( 0 )

starting LICHESS connection at:  2018-06-27 01:48:49

ERROR:backoff:Backing off watch_control_stream(...) for 0.0s (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
ERROR:backoff:Giving up watch_control_stream(...) after 2 tries (json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0))
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "lichess-bot.py", line 41, in watch_control_stream
    event = json.loads(evnt.decode('utf-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

starting LICHESS connection at:  2018-06-27 04:09:09

starting LICHESS connection at:  2018-06-27 04:14:21

ERROR:backoff:Backing off watch_control_stream(...) for 0.8s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))
ERROR:backoff:Backing off watch_control_stream(...) for 1.5s (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
ERROR:backoff:Giving up watch_control_stream(...) after 3 tries (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
Process Process-2:
Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 543, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 547, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "lichess-bot.py", line 39, in watch_control_stream
    for evnt in li.get_event_stream().iter_lines():
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 789, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

starting LICHESS connection at:  2018-06-27 04:50:46

ERROR:backoff:Backing off watch_control_stream(...) for 0.6s (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
ERROR:backoff:Giving up watch_control_stream(...) after 2 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/stream/event (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75e70a10>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Process Process-2:
Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x75e70a10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/stream/event (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75e70a10>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "lichess-bot.py", line 39, in watch_control_stream
    for evnt in li.get_event_stream().iter_lines():
  File "/home/beco/Documents/fontes/python/lichess-bot/lichess.py", line 82, in get_event_stream
    return requests.get(url, headers=self.header, stream=True)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/stream/event (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75e70a10>: Failed to establish a new connection: [Errno 111] Connection refused',))

starting LICHESS connection at:  2018-06-27 05:06:22

ERROR:backoff:Backing off api_get(...) for 0.6s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))
ERROR:backoff:Backing off api_get(...) for 1.6s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))
ERROR:backoff:Backing off api_get(...) for 3.7s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))

starting LICHESS connection at:  2018-06-27 05:11:33

ERROR:backoff:Backing off api_get(...) for 0.3s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))
ERROR:backoff:Backing off watch_control_stream(...) for 0.5s (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
ERROR:backoff:Backing off watch_control_stream(...) for 0.5s (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
ERROR:backoff:Giving up watch_control_stream(...) after 3 tries (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
Process Process-2:
Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 543, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 547, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "lichess-bot.py", line 39, in watch_control_stream
    for evnt in li.get_event_stream().iter_lines():
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 789, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/home/beco/Documents/fontes/python/lichess-bot/.venv/lib/python3.5/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))


starting LICHESS connection at:  2018-06-27 05:37:34


ERROR:backoff:Backing off watch_control_stream(...) for 0.4s (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))

starting LICHESS connection at:  2018-06-27 05:47:57

ERROR:backoff:Backing off api_get(...) for 0.7s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))

starting LICHESS connection at:  2018-06-27 05:53:10

ERROR:backoff:Backing off api_get(...) for 0.3s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))
ERROR:backoff:Backing off api_get(...) for 1.6s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))
ERROR:backoff:Backing off watch_control_stream(...) for 0.8s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))
ERROR:backoff:Backing off watch_control_stream(...) for 1.0s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))
ERROR:backoff:Backing off watch_control_stream(...) for 3.7s (requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error')))
```

I call your attention to the line 

```
starting LICHESS connection at:  2018-06-27 xx:xx:xx
```

This is the log that tells the meta-script checking if lichess-bot is alive decided to start it over again. So it is a fresh start for lichess-bot from this point on. And it starts with an error. 

Thanks a lot.

Keep up the good work!

Beco

**Comment by gbtami** [comment]
Same here with PyChessBot. There was a server restart that time or something like that. Maybe that caused this.

**Comment by ddugovic** [comment]
As for "3 tries" (instead of "1 try") see https://github.com/ddugovic/lichess-bot/commit/d3083f1be650255404d6217c15121468f76084c4

**Comment by careless25** [comment]
Just merged this pr: https://github.com/careless25/lichess-bot/pull/133
