### ISSUE TITLE
Error logging an error

### ISSUE THREAD

**Issue by ddugovic** [careless25/lichess-bot#148]
```
Nov 16 00:25:33 vps178028 python3[923]: 2018-11-16 00:25:33,850: Giving up watch_control_stream(...) after 2 tries (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
Nov 16 00:25:33 vps178028 python3[923]: Process Process-2:
Nov 16 00:25:33 vps178028 python3[923]: Traceback (most recent call last):
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 601, in _update_chunk_length
Nov 16 00:25:33 vps178028 python3[923]: ValueError: invalid literal for int() with base 16: b''
Nov 16 00:25:33 vps178028 python3[923]: During handling of the above exception, another exception occurred:
Nov 16 00:25:33 vps178028 python3[923]: Traceback (most recent call last):
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
Nov 16 00:25:33 vps178028 python3[923]:     yield
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 666, in read_chunked
Nov 16 00:25:33 vps178028 python3[923]:     self._update_chunk_length()
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 605, in _update_chunk_length
Nov 16 00:25:33 vps178028 python3[923]:     raise httplib.IncompleteRead(line)
Nov 16 00:25:33 vps178028 python3[923]: http.client.IncompleteRead: IncompleteRead(0 bytes read)
Nov 16 00:25:33 vps178028 python3[923]: During handling of the above exception, another exception occurred:
Nov 16 00:25:33 vps178028 python3[923]: Traceback (most recent call last):
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/requests/models.py", line 750, in generate
Nov 16 00:25:33 vps178028 python3[923]:     for chunk in self.raw.stream(chunk_size, decode_content=True):
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 490, in stream
Nov 16 00:25:33 vps178028 python3[923]:     for line in self.read_chunked(amt, decode_content=decode_content):
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 694, in read_chunked
Nov 16 00:25:33 vps178028 python3[923]:     self._original_response.close()
Nov 16 00:25:33 vps178028 python3[923]:   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
Nov 16 00:25:33 vps178028 python3[923]:     self.gen.throw(type, value, traceback)
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 378, in _error_catcher
Nov 16 00:25:33 vps178028 python3[923]:     raise ProtocolError('Connection broken: %r' % e, e)
Nov 16 00:25:33 vps178028 python3[923]: urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Nov 16 00:25:33 vps178028 python3[923]: During handling of the above exception, another exception occurred:
Nov 16 00:25:33 vps178028 python3[923]: Traceback (most recent call last):
Nov 16 00:25:33 vps178028 python3[923]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Nov 16 00:25:33 vps178028 python3[923]:     self.run()
Nov 16 00:25:33 vps178028 python3[923]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
Nov 16 00:25:33 vps178028 python3[923]:     self._target(*self._args, **self._kwargs)
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/backoff/_sync.py", line 99, in retry
Nov 16 00:25:33 vps178028 python3[923]:     ret = target(*args, **kwargs)
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/lichess-bot/lichess-bot.py", line 42, in watch_control_stream
Nov 16 00:25:33 vps178028 python3[923]:     for evnt in li.get_event_stream().iter_lines():
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/requests/models.py", line 794, in iter_lines
Nov 16 00:25:33 vps178028 python3[923]:     for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
Nov 16 00:25:33 vps178028 python3[923]:   File "/home/turing/.local/lib/python3.6/site-packages/requests/models.py", line 753, in generate
Nov 16 00:25:33 vps178028 python3[923]:     raise ChunkedEncodingError(e)
Nov 16 00:25:33 vps178028 python3[923]: requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by gbtami** [comment]
I think this can be closed after latest commits.
