### ISSUE TITLE
Fully terminate client when lichess is down doesn't work

### ISSUE THREAD

**Issue by gbtami** [careless25/lichess-bot#167]
https://github.com/careless25/lichess-bot/commit/5ca949973a3642e08e3745351efb2940cba96606#diff-eb42f63c72056ec1f9fcba336dae222a is not working because 1. sys.exit() terminates only the control stream subprocess, 2. `terminated` can't be set from a subprocess.

**Comment by gbtami** [comment]
Today morning a faced that PyChessBot is offline because of this:
```
2019-01-21T05:35:39.111470+00:00 app[worker.1]: 

2019-01-21T05:35:39.111471+00:00 app[worker.1]: Traceback (most recent call last):

2019-01-21T05:35:39.111472+00:00 app[worker.1]:   File "lichess-bot.py", line 57, in watch_control_stream

2019-01-21T05:35:39.111473+00:00 app[worker.1]:     for line in response.iter_lines():

2019-01-21T05:35:39.111475+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/models.py", line 794, in iter_lines

2019-01-21T05:35:39.111477+00:00 app[worker.1]:     for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):

2019-01-21T05:35:39.111478+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/models.py", line 753, in generate

2019-01-21T05:35:39.111479+00:00 app[worker.1]:     raise ChunkedEncodingError(e)

2019-01-21T05:35:39.111484+00:00 app[worker.1]: requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

2019-01-21T05:35:39.112244+00:00 app[worker.1]: 2019-01-21 05:35:39 backoff[16] [1mINFO[0m [94mBacking off watch_control_stream(...) for 0.4s (SystemExit)[0m
```

Merge https://github.com/careless25/lichess-bot/pull/168 , please!
