### ISSUE TITLE
can't handle "ebf" in uci progress reports

### ISSUE THREAD

**Issue by flok99** [careless25/lichess-bot#46]
```
ValueError: invalid literal for int() with base 10: '1.00'
ERROR:chess.engine:exception parsing score cp value
Traceback (most recent call last):
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/chess/uci.py", line 534, in _info
    score_cp = int(token)
ValueError: invalid literal for int() with base 10: 'ebf'
ERROR:chess.engine:exception parsing score cp value
Traceback (most recent call last):
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/chess/uci.py", line 534, in _info
    score_cp = int(token)
```

```
info depth 1 seldepth 1 score cp 106 time 2 nodes 21 pv e2e4
info depth 2 seldepth 4 score cp 21 time 3 nodes 74 pv e2e4
info depth 2 seldepth 4 score cp 0 ebf 1.75 time 4 nodes 138 pv e2e4 e7e5
```

**Comment by gbtami** [comment]
I think this should be fixed in python-chess not in lichess-bot.

**Comment by ornicar** [comment]
Indeed. Make an issue on niklasf/python-chess

**Comment by ZirconiumX** [comment]
To be fair, you're using a non-standard UCI command and wondering why it isn't portable.
