### ISSUE TITLE
Crashing when accepting game

### ISSUE THREAD

**Issue by JABirchall** [careless25/lichess-bot#50]
Dump:
```
.   _/|
.  // o\
.  || ._)  lichess-bot 0.2
.  //__\
.  )___(   Play on Lichess with a bot

Welcome LeelaZero-UK!
    Queue Bullet challenge from leonrades
    Accept Bullet challenge from leonrades
--- Process Queue. Total Queued: 1. Total Used: 0
--- Process Used. Total Queued: 0. Total Used: 1
Traceback (most recent call last):
  File "G:\lichess-bot\logging_pool.py", line 16, in __call__
    result = self.__callable(*args, **kwargs)
  File "G:\lichess-bot\main.py", line 96, in play_game
    engine = engine_factory(board)
  File "G:\lichess-bot\engine_wrapper.py", line 27, in create_engine
    return UCIEngine(board, commands, ucioptions)
  File "G:\lichess-bot\engine_wrapper.py", line 104, in __init__
    self.engine = chess.uci.popen_engine(commands)
  File "G:\lichess-bot\.venv\lib\site-packages\chess\uci.py", line 1138, in popen_engine
    return _popen_engine(command, engine_cls, setpgrp, _popen_lock, **kwargs)
  File "G:\lichess-bot\.venv\lib\site-packages\chess\engine.py", line 315, in _popen_engine
    PopenProcess(engine, command, **popen_args)
  File "G:\lichess-bot\.venv\lib\site-packages\chess\engine.py", line 145, in __init__
    self.process = subprocess.Popen(command, **popen_args)
  File "C:\Python3\Lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Python3\Lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)
  File "C:\Python3\Lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
```

**Comment by careless25** [comment]
In your config, one of your parameters needs to be in quotes (string vs int error). We will fix this in a later release.

**Comment by JABirchall** [comment]
Which one? This is my config

```
token: "ommitted"    # lichess OAuth2 Token
url: "https://lichess.org/"  # lichess base URL

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "lczero.exe"         # binary name of the engine to use
  protocol: "uci"            # "uci" or "xboard"
  weights: "latest"          # only if the engine is lczero
  threads: 4                 # only if the engine is lczero

#ucioptions:
#  Threads: 4
#  Hash: "4096"
#  Book File: "engines/book.bin"


max_concurrent_games: 2      # number of games to play simultaneously
max_queued_challenges: 8     # number of challenges to allow to queue

supported_variants:          # chess variants to accept (http://lichess.org/variant)
  - standard
#  - fromPosition
#  - antichess
#  - atomic
#  - chess960
#  - crazyhouse
#  - horde
#  - kingOfTheHill
#  - racingKings
#  - threeCheck

supported_tc:                # time controls to accept
  - ultraBullet
  - bullet
  - blitz
  - rapid
  - classical
#  - correspondence

supported_modes:             # game modes to accept
  - casual                   # unrated games
  - rated                    # rated games - must comment if the engine doesn't try to win

print_engine_stats: false    # print engine stats on each move
```

**Comment by JABirchall** [comment]
Figured it out, engine.threads needs to be in quotes.
