### ISSUE TITLE
Bad Request for url

### ISSUE THREAD

**Issue by gbtami** [careless25/lichess-bot#72]
PyChessBot losed this game on time because it's latest move can't get through in this position:
https://lichess.org/cv25KskE#58

The relevant log was:
```
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> >> move Rxh7
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "POST /bot/game/cv25KskE/move/b7h7 HTTP/1.1" 200 None
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> << force
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> << setboard 6r1/p6R/2p5/8/4Pk2/5P1B/PP1N1P1P/2K5 w - - 1 30
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> << time 81.0
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> << otim 339.0
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> << go
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> >> # Time left: 0.81 s; Planing to think for 2.00 s
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> >> 1 2853 0 39 Rxa7
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> >> 2 2846 4 302 Rf7+ Ke5 Rxa7
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> >> 3 2902 14 1240 Rf7+ Kg5 Rxa7
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> >> 4 2853 57 4636 Rf7+ Kg5 Rxa7 Kf4
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> >> move Rf7+
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "POST /bot/game/cv25KskE/move/h7f7 HTTP/1.1" 400 None
ERROR:backoff:Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/bot/game/cv25KskE/move/h7f7)
Abandoning game due to connection error
Traceback (most recent call last):
  File "main.py", line 128, in play_game
    li.make_move(game.id, best_move)
  File "/home/tamas/lichess-bot/lichess.py", line 68, in make_move
    return self.api_post(ENDPOINTS["move"].format(game_id, move))
  File "/usr/local/lib/python3.5/dist-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/home/tamas/lichess-bot/lichess.py", line 58, in api_post
    response.raise_for_status()
  File "/home/tamas/.local/lib/python3.5/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/bot/game/cv25KskE/move/h7f7
--- https://lichess.org//cv25KskE/white Game over
DEBUG:chess.engine:<PopenProcess at 0x7f368a5782e8 (pid=2500)> << quit
+++ Process Free. Total Queued: 0. Total Used: 0
```

Is this a lichess-bot bug or something else?

**Comment by ddugovic** [comment]
Hmm...

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/bot/game/cv25KskE/move/h7f7
--- https://lichess.org//cv25KskE/white Game over
```

**Comment by gbtami** [comment]
Thx!

**Comment by gbtami** [comment]
@ddugovic finally I was able to track this down.
The line caused losing on time was the misleading st commant in first_search() at https://github.com/careless25/lichess-bot/blob/master/engine_wrapper.py#L150
sigh
