### ISSUE TITLE
Client Error: Unauthorized for url: https://lichess.org/account/me

### ISSUE THREAD

**Issue by ProxyOps** [careless25/lichess-bot#85]
(.venv) PS C:\Users\nikla\Desktop\beabot> python main.py
.   _/|
.  // o\
.  || ._)  lichess-bot 0.10
.  //__\
.  )___(   Play on Lichess with a bot

ERROR:backoff:Giving up api_get(...) after 1 tries (requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://lichess.org/account/me)
Traceback (most recent call last):
  File "main.py", line 240, in <module>
    user_profile = li.get_profile()
  File "C:\Users\nikla\Desktop\beabot\lichess.py", line 96, in get_profile
    profile = self.api_get(ENDPOINTS["profile"])
  File "C:\Users\nikla\Desktop\beabot\.venv\lib\site-packages\backoff\_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "C:\Users\nikla\Desktop\beabot\lichess.py", line 52, in api_get
    response.raise_for_status()
  File "C:\Users\nikla\Desktop\beabot\.venv\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://lichess.org/account/me

**Comment by ornicar** [comment]
Sorry about that, the next lichess deploy (in about one hour) will fix it.
